<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_manipulator">

    <!-- ================= PARAMETERS ================= -->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.15" />

    <xacro:property name="wheel_radius" value="0.08" />
    <xacro:property name="wheel_width" value="0.04" />

    <!-- math -->
    <xacro:property name="base_z" value="${wheel_radius + base_height/2}" />
    <xacro:property name="wheel_x" value="${base_length/2 - wheel_radius}" />
    <xacro:property name="wheel_y" value="${base_width/2 + wheel_width/2}" />
    <xacro:property name="wheel_z" value="${wheel_radius}" />

    <!-- arm mount -->
    <xacro:property name="arm_mount_x" value="-0.22" />
    <xacro:property name="arm_mount_y" value="0.0" />
    <xacro:property name="arm_mount_z" value="${base_z + base_height/2 + 0.01}" />

    <!-- ================= BASE LINK ================= -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_z}" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${base_z}" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${base_z}" />
            <mass value="25.0" />
            <inertia
                ixx="${(1/12)*25.0*(base_width*base_width + base_height*base_height)}"
                iyy="${(1/12)*25.0*(base_length*base_length + base_height*base_height)}"
                izz="${(1/12)*25.0*(base_length*base_length + base_width*base_width)}"
                ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <!-- ================= WHEEL MACRO ================= -->
    <xacro:macro name="wheel" params="name">
        <link name="${name}">
            <visual>
                <origin xyz="0 0 0" rpy="1.5708 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.5708 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
            </collision>
            <inertial>
                <mass value="1.0" />
                <inertia ixx="0.001" iyy="0.001" izz="0.002" ixy="0" ixz="0" iyz="0" />
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel name="wheel_front_left" />
    <xacro:wheel name="wheel_front_right" />
    <xacro:wheel name="wheel_rear_left" />
    <xacro:wheel name="wheel_rear_right" />

    <!-- ================= WHEEL JOINTS ================= -->
    <joint name="left_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="wheel_front_left" />
        <origin xyz="${ wheel_x} ${ wheel_y} ${wheel_z}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="left_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="wheel_rear_left" />
        <origin xyz="${-wheel_x} ${ wheel_y} ${wheel_z}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="right_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="wheel_front_right" />
        <origin xyz="${ wheel_x} ${-wheel_y} ${wheel_z}" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="right_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="wheel_rear_right" />
        <origin xyz="${-wheel_x} ${-wheel_y} ${wheel_z}" />
        <axis xyz="0 1 0" />
    </joint>

    <!-- ================= LIDAR ================= -->
    <link name="lidar_link">
        <visual>
            <origin xyz="0 0 0" />
            <geometry>
                <cylinder radius="0.04" length="0.05" />
            </geometry>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1" />
            </material>
        </visual>

        <collision>
            <origin xyz="0 0 0" />
            <geometry>
                <cylinder radius="0.04" length="0.05" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" />
            <mass value="0.3" />
            <inertia ixx="0.0005" iyy="0.0005" izz="0.0005"
                ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="0 0 ${arm_mount_z}" />
    </joint>
    <!-- ================= BASE CAMERA ================= -->
    <link name="base_camera_link">
        <visual>
            <origin xyz="0 0 0" />
            <geometry>
                <box size="0.04 0.04 0.04" />
            </geometry>
            <material name="gray">
                <color rgba="1 0.5 0.5 1" />
            </material>
        </visual>
    </link>


    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_camera_link" />
        <origin xyz="0.3 0 ${arm_mount_z - 0.04}" />
    </joint>

    <!-- ================= ARM ================= -->

    <joint name="shoulder_joint" type="revolute">
        <parent link="base_link" />
        <child link="shoulder_link" />
        <origin xyz="${arm_mount_x} ${arm_mount_y} ${arm_mount_z}" />
        <axis xyz="0 0 1" />
        <limit lower="-3.14" upper="3.14" effort="300" velocity="1" />
    </joint>

    <link name="shoulder_link">
        <visual>
            <origin xyz="0 0 0.2" />
            <geometry>
                <cylinder length="0.4" radius="0.04" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.2" />
            <geometry>
                <cylinder length="0.4" radius="0.04" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.2" />
            <mass value="2" />
            <inertia ixx="0.02" iyy="0.02" izz="0.02" ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="elbow_joint" type="revolute">
        <parent link="shoulder_link" />
        <child link="elbow_link" />
        <origin xyz="0 0 0.4" />
        <axis xyz="1 0 0" />
        <limit lower="-1.57" upper="1.57" effort="300" velocity="1" />
    </joint>

    <link name="elbow_link">
        <visual>
            <origin xyz="0 0 0.2" />
            <geometry>
                <cylinder length="0.4" radius="0.035" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.2" />
            <geometry>
                <cylinder length="0.4" radius="0.035" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.2" />
            <mass value="1.5" />
            <inertia ixx="0.015" iyy="0.015" izz="0.015" ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="forearm_joint" type="revolute">
        <parent link="elbow_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 0.4" />
        <axis xyz="1 0 0" />
        <limit lower="-1.57" upper="1.57" effort="300" velocity="1" />
    </joint>

    <link name="forearm_link">
        <visual>
            <origin xyz="0 0 0.15" />
            <geometry>
                <cylinder length="0.3" radius="0.03" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.15" />
            <geometry>
                <cylinder length="0.3" radius="0.03" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.15" />
            <mass value="1" />
            <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="wrist_pitch_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="wrist_pitch_link" />
        <origin xyz="0 0 0.3" />
        <axis xyz="1 0 0" />
        <limit lower="-1.57" upper="1.57" effort="100" velocity="1" />
    </joint>

    <link name="wrist_pitch_link">
        <visual>
            <origin xyz="0 0 0.04" />
            <geometry>
                <cylinder length="0.08" radius="0.025" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.04" />
            <geometry>
                <cylinder length="0.08" radius="0.025" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.04" />
            <mass value="0.4" />
            <inertia ixx="0.002" iyy="0.002" izz="0.002" ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="wrist_roll_joint" type="revolute">
        <parent link="wrist_pitch_link" />
        <child link="wrist_roll_link" />
        <origin xyz="0 0 0.08" />
        <axis xyz="0 0 1" />
        <limit lower="-3.14" upper="3.14" effort="50" velocity="2" />
    </joint>

    <link name="wrist_roll_link">
        <visual>
            <origin xyz="0 0 0.03" />
            <geometry>
                <cylinder length="0.06" radius="0.022" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.03" />
            <geometry>
                <cylinder length="0.06" radius="0.022" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.03" />
            <mass value="0.3" />
            <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="gripper_mount_joint" type="fixed">
        <parent link="wrist_roll_link" />
        <child link="gripper_base" />
        <origin xyz="0 0 0.06" />
    </joint>

    <link name="gripper_base">
        <visual>
            <origin xyz="0 0 0.05" />
            <geometry>
                <box size="0.08 0.08 0.1" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.05" />
            <geometry>
                <box size="0.08 0.08 0.1" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.05" />
            <mass value="0.4" />
            <inertia ixx="0.002" iyy="0.002" izz="0.002" ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="gripper_base" />
        <child link="camera_link" />
        <origin xyz="0 0 0.08" rpy="0 -1.57 0" />
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.04 0.04 0.04" />
            </geometry>
        </visual>
    </link>

    <joint name="left_finger_joint" type="prismatic">
        <parent link="gripper_base" />
        <child link="left_finger" />
        <origin xyz="0 0.012 0.05" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="0.025" effort="100" velocity="0.2" />
    </joint>

    <link name="left_finger">
        <visual>
            <origin xyz="0 0 0.05" />
            <geometry>
                <box size="0.015 0.015 0.1" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.05" />
            <geometry>
                <box size="0.015 0.015 0.1" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.05" />
            <mass value="0.05" />
            <inertia ixx="0.0002" iyy="0.0002" izz="0.0002" ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="right_finger_joint" type="prismatic">
        <parent link="gripper_base" />
        <child link="right_finger" />
        <origin xyz="0 -0.012 0.05" />
        <axis xyz="0 -1 0" />
        <limit lower="0" upper="0.025" effort="100" velocity="0.2" />
    </joint>

    <link name="right_finger">
        <visual>
            <origin xyz="0 0 0.05" />
            <geometry>
                <box size="0.015 0.015 0.1" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.05" />
            <geometry>
                <box size="0.015 0.015 0.1" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.05" />
            <mass value="0.05" />
            <inertia ixx="0.0002" iyy="0.0002" izz="0.0002" ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <gazebo reference="lidar_link">
        <sensor name="gpu_lidar" type="gpu_lidar">
            <update_rate>10</update_rate>
            <topic>scan</topic>
            <gz_frame_id>lidar_link</gz_frame_id>
            <frame_id>lidar_link</frame_id>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>180</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14156</min_angle>
                        <max_angle>3.14156</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.05</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </lidar>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>
    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <update_rate>30</update_rate>
            <topic>/arm_camera/image</topic>
            <camera>
                <horizontal_fov>1.396</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
            </camera>
        </sensor>
    </gazebo>
    <gazebo reference="base_camera_link">
        <sensor name="camera" type="camera">
            <update_rate>30</update_rate>
            <topic>/base_camera/image</topic>
            <camera>
                <horizontal_fov>1.396</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
            </camera>
        </sensor>
    </gazebo>
    <gazebo>
        <plugin
            filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>
    </gazebo>
    <!-- ================= GAZEBO DIFF DRIVE ================= -->
    <gazebo>
        <plugin filename="libgz-sim-diff-drive-system.so" name="gz::sim::systems::DiffDrive">
            <left_joint>left_front_wheel_joint</left_joint>
            <left_joint>left_rear_wheel_joint</left_joint>
            <right_joint>right_front_wheel_joint</right_joint>
            <right_joint>right_rear_wheel_joint</right_joint>
            <wheel_separation>${base_width - wheel_width}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <skid_steer>true</skid_steer>
            <topic>/cmd_vel</topic>
            <odom_topic>/odom</odom_topic>
            <frame_id>odom</frame_id>
            <tf_topic>/tf</tf_topic>
            <child_frame_id>base_link</child_frame_id>
            <odom_publish_frequency>30</odom_publish_frequency>
        </plugin>
        <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic>
            <joint_name>left_front_wheel_joint</joint_name>
            <joint_name>right_front_wheel_joint</joint_name>
            <joint_name>left_rear_wheel_joint</joint_name>
            <joint_name>right_rear_wheel_joint</joint_name>
        </plugin>
    </gazebo>
    <!-- ================= ROS2 CONTROL ================= -->
    <ros2_control name="mobile_manipulator_arm" type="system">
        <hardware>
            <plugin>gz_ros2_control/GazeboSimSystem</plugin>
        </hardware>

        <joint name="shoulder_joint">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>

        <joint name="elbow_joint">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>

        <joint name="forearm_joint">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>

        <joint name="wrist_pitch_joint">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>

        <joint name="wrist_roll_joint">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>

        <joint name="left_finger_joint">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>

        <joint name="right_finger_joint">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
        </joint>
    </ros2_control>
    <!-- ================= GAZEBO ROS2 CONTROL PLUGIN ================= -->
    <gazebo>
        <plugin filename="libgz_ros2_control-system.so"
            name="gz_ros2_control::GazeboSimROS2ControlPlugin">
            <parameters>
                /home/madhu/ros2_nexus_fleet_ws/install/fleet_description/share/fleet_description/config/controllers.yaml
            </parameters>
        </plugin>
    </gazebo>

</robot>